### ISSUE TITLE
Relax canceling Leave of Absence

### ISSUE THREAD

**Issue by sparrell** [oasis-board-process-committee/TC-Process#21]
https://www.oasis-open.org/policies-guidelines/tc-process-2017-05-26/#leavesAbsence (and equivalent in OP) states

> Voting rights shall resume immediately when the Leave ends, upon any activity (including activity on the TC mailing list) in the TC by the Member, or earlier if requested by the Member.

I request reevaluating the "including activity on the TC mailing list" as I consider it counter productive

**Comment by OASIS-OP-Admin** [comment]
To provide a bit of history:  the LoA policy has been a problem for as long as I've been at OASIS. The Process Committee took runs at it multiple times. If I remember correctly, when I started here in 2011, that section was almost a full page of if/then/else/unless/of course/maybe type verbiage that required several steps by the requester and the TC. The last time we reworked it - leading to the current policy - we were trying to simplify it and remove the need of the TC to do explicit work to approve leaves. The idea behind the email phrase, as I recall, was that if you're on leave, you are on leave period. You shouldn't be semi-engaged. 

I think what has been the problem has been not being clear on the point of the policy. I've always thought the main purpose was to let people take breaks without losing their voting member status. Kavi has an LoA role that the chair can set that will keep the member from showing up on ballots and quorum and such though very few know that or use it. 

Personally, if that is the main goal with LoA, then I think a person on leave shouldn't vote but the email proscription seems excessive. I don't see a problem with relaxing it.

**Comment by jordan2175** [comment]
I do not see a problem with relaxing it either. Some of the history around this was to accommodate our European members that often take an entire month off during the summer. It was revised 4-5 years ago to address two problems, 1) the TC needing to approve a LoA, 2) individuals using the LoA policy to get around losing voting rights if they cannot come to a meeting because they were double booked. Some individuals used the LoA policy for a length of a single day and used it repeatedly. That was never the purpose of the policy.

**Comment by jordan2175** [comment]
We talked about this today during the process committee meeting and the consensus is we will not fix this.

Maybe add to the definition the types of activities that would qualify for an LoA. Maybe have an alternate instead?
