### ISSUE TITLE
Why do we have this document, OASIS Committee Operations Process?

### ISSUE THREAD

**Issue by jordan2175** [oasis-board-process-committee/TC-Process#28]
I am not sure why we have a separate document that basically says the same things but differently than the TC Process document. We should be consistent and use one document or at least not repeat content.

**Comment by OASIS-OP-Admin** [comment]
Bret, it was created when we were developing open projects. At the time, we just had the TC Process. Because of all the differences between it and the op process, we couldn't easily make it one doc to cover both. Since we needed a OP Process doc, we decided to pull the material that would be common for both TC and OP - as well as any other committee that might be created - into the Committee Operations process. The TC and OP process docs shouldn't duplicate the content but instead build on it.

**Comment by jordan2175** [comment]
I think we should re-look at this document and how we have the documents broken up after we finish discussing how OPs should work in relation to TCs.
